### PR TITLE
Signedness support

### PR DESCRIPTION
**Pull request by alexsnaps**
This updates to the v0.0.8 of `nom-sql` and adds the bits to handle unsigned `SqlType::UnsignedInt`, `UnsignedBigint` & `UnsignedTinyint` to the shim.

I think that's all that's needed 🙈

### CODE REVIEW

**Comment by alexsnaps** [comment]
Looks like I broke… "some" stuff

**Comment by ms705** [comment]
A quick check suggests the problems are introduced by the `nom-sql` upgrade (or other dependency upgrades).

**Comment by ms705** [comment]
Further update: the Noria side is fine, it adds the queries as expected (verified by `VERBOSE=1 cargo test update_basic_prepared -- --nocapture`). So the problem must be in the shim.

**Comment by ms705** [comment]
Update: chased it down further. It looks like we end up with filter operators comparing unsigned and signed integers. A query like `SELECT Cats.name FROM Cats WHERE Cats.id = 1` results in having a filter operator in the dataflow that incorrectly rejects records:
```
d: UnsignedBigInt(1), v: BigInt(1)
res: false
```
... which is clearly bogus.

**Comment by ms705** [comment]
Fixed some of the damage in mit-pdos/noria@0c00674, but I'm now getting errors like:
```
thread '<unnamed>' panicked at 'failed to write column: Custom { kind: InvalidData, error: "tried to use 4 as MYSQL_TYPE_LONG" }', src/backend.rs:816:27
```
... which seems more firmly rooted in this PR.

**Comment by alexsnaps** [comment]
Yeah, writing anything else than the `isize` to `rw.write_col` makes it all fail. 
Actually was surprised that's even an `isize` to be honest… but I'll look into what goes on there.

**Comment by ms705** [comment]
This could be a restriction imposed by the `msql_srv` library code; @jonhoo might know more.On Aug 22, 2019 09:01, Alex Snaps <notifications@github.com> wrote:Yeah, writing anything else than the isize to rw.write_col makes it all fail.

Actually was surprised that's even an isize to be honest… but I'll look into what goes on there.

**Comment by jonhoo** [comment]
Hmm.. I believe the MySQL binary protocol only allows number up to 64 bits, so that's probably what you're running into :/

**Comment by alexsnaps** [comment]
Yes, based on what I see things go wrong with `PreparedStatement`. I _think_ some stuff exploses with literals (and my branch locally uses the latest patch I put out for nom-sql that stores Integer literals as i128…
Trying to hunt this down in all the inference that happens. Nonetheless tho, why were `i32` written as `isize`? Is there a reason for this? I can see `i64` being an issue as `isize` on non 64 bit systems, which might be out of scope, but…

**Comment by alexsnaps** [comment]
Just a quick update: We've worked around this failure to try and test further. I'll try to make some time in the evenings to work and fix the other failures left. This still requires using the latest `nom-sql` as the implementation of the `Display` trait was wrong, its output needs to be reparsable SQL (as the shim parses and re-outputs SQL to noria in certain cases, e.g. TABLE creation).
I'll clean things up a bit and push PRs to the different repos asap...

**Comment by ms705** [comment]
Both `noria` and `noria-mysql` now use the latest `nom-sql`, fixing the parseable output issue. Looks like I created conflicts for this PR though; sorry about that! Will fix and merge.

Can you let us know what the other remaining problems are? (Through issues, or list here, or by email.) We can then have a go at solving some of those, so that it doesn't all fall to you.

**Pull request merged**
