### PR TITLE
Add listen address argument

### LINKED ISSUE #12: Add listen address argument
I was playing around with noria on a cluster environment, and noticed that the mysql adapter only listens on a localhost address. Could we allow the mysql-adapter to have an additional argument `--address`, which points to the listen address, similar to how `noria-server` does it ? e.g. https://github.com/fussybeaver/noria-mysql/commit/e7c2238d198f900c12bd32d371a8ea67137082f3

I also had to peg the noria dependency at an older revision to get it to compile, because I think the `Row` interface was changed recently? I wasn't sure what was needed to fix that..

### PR DESCRIPTION
**Pull request by fussybeaver**
Removes the `--port` argument and combines `host:port` into an `--address` argument as the listen address.

Fixes #12

### CODE REVIEW

**Comment by jonhoo** [comment]
Looks great to me! @ms705 ?

**Comment by ms705** [comment]
Looks good, thanks @fussybeaver! :+1:

**Comment by ms705** [comment]
(Travis failures seem unrelated to this PR, but are curious. Did the `mysql` interfaces change?)

**Comment by jonhoo** [comment]
@ms705 Oh, yes, it did! It's mostly a matter of different imports due to trait reorganization though.

**Pull request merged**
